=== MorniingRay/XML-Project---contact-list-parsing/out/production/java_xml/contacts9.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:contacts="http://www.example.com/contacts"
        targetNamespace="http://www.example.com/contacts"
        elementFormDefault="qualified">
    <attributeGroup name="ContactAttributes">
        <attribute name="version" type="decimal" fixed="1.0"/>
        <attribute name="source" type="string"/>
    </attributeGroup>

    <element name="contacts">
        <complexType>
            <sequence>
                <element name="contact" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="contacts:NameType"/>
                            <element name="location" type="contacts:LocationType"/>
                            <element name="phone" type="contacts:PhoneType"/>
                            <element name="knows" type="contacts:KnowsType"/>
                            <element name="description" type="contacts:DescriptionType"/>
                        </sequence>
                        <attribute name="tags" type="token"/>
                        <attribute name="person" type="ID"/>
                    </complexType>
                </element>
            </sequence>
            <attributeGroup ref="contacts:ContactAttributes"/>
        </complexType>
    </element>

    <complexType name="NameType">
        <group ref="contacts:NameGroup"/>
        <attribute name="title" type="string"/>
    </complexType>

    <group name="NameGroup">
        <sequence>
            <element name="first" type="string" minOccurs="1" maxOccurs="unbounded"/>
            <element name="middle" type="string" minOccurs="0" maxOccurs="1"/>
            <element name="last" type="string"/>
        </sequence>
    </group>

    <complexType name="LocationType">
        <choice minOccurs="0" maxOccurs="unbounded">
            <element name="address" type="string"/>
            <sequence>
                <element name="latitude" type="float"/>
                <element name="longitude" type="float"/>
            </sequence>
        </choice>
    </complexType>

    <complexType name="PhoneType">
        <simpleContent>
            <extension base="string">
                <attribute name="kind" type="string" default="Home"/>
            </extension>
        </simpleContent>
    </complexType>

    <complexType name="KnowsType">
        <attribute name="contacts" type="IDREFS"/>
    </complexType>

    <complexType name="DescriptionType" mixed="true">
        <choice minOccurs="0" maxOccurs="unbounded">
            <element name="em" type="string"/>
            <element name="strong" type="string"/>
            <element name="br" type="string"/>
        </choice>
    </complexType>

</schema>

=== MorniingRay/XML-Project---contact-list-parsing/out/artifacts/java_xml_war_exploded/WEB-INF/classes/contacts9.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<contacts xmlns="http://www.example.com/contacts" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          source="Beginning XML 4E" version="1.0" xsi:schemaLocation="http://www.example.com/contacts contacts9.xsd">
    <contact person="Jeff_Rafter" tags="author xml poetry">
        <name title="Mr.">
            <first>Jeff</first>
            <middle>Craig</middle>
            <last>Rafter</last>
        </name>
        <location>
            <address>Redlands, CA, USA</address>
            <latitude>34.031892</latitude>
            <longitude>-117.207642</longitude>
        </location>
        <phone kind="Home">001-909-555-1212</phone>
        <knows contacts="David_Hunter Danny_Ayers"/>
        <description>
            Jeff is a developer and author for Beginning XML <em>4th edition</em>.<br/>Jeff
            <strong>loves</strong>
            XML!
        </description>
    </contact>


    <contact person="David_Hunter" tags="author consultant CGI">
        <name>
            <first>David</first>
            <last>Hunter</last>
        </name>
        <location>
            <address>Address is not known</address>
        </location>
        <phone kind="Work">416 555 1212</phone>
        <knows contacts="Jeff_Rafter Danny_Ayers"/>
        <description>Senior Technical Consultant for CGI.</description>
    </contact>


    <contact person="Danny_Ayers" tags="author semantics animals">
        <name>
            <first>Daniel</first>
            <middle>John</middle>
            <last>Ayers</last>
        </name>
        <location>
            <latitude>43.847156</latitude>
            <longitude>10.50808</longitude>
            <address>Mozzanella, 7 Castiglione di Garfagnana, 55033 Lucca Italy</address>
        </location>
        <phone>+39-0555-11-22-33-</phone>
        <knows contacts="Jeff_Rafter David_Hunter"/>
        <description>A Semantic Web developer and technical author specializing in cutting-edge technologies.
        </description>
    </contact>


    <contact person="weqwe" tags="qwe">
        <name title="we">
            <first>wQQWEQe</first>
            <middle>weqwe</middle>
            <last>eqwe</last>
        </name>
        <location>
            <address>e</address>
            <latitude>33</latitude>
            <longitude>44</longitude>
        </location>
        <phone kind="qwe">123123</phone>
        <knows contacts="David_Hunter"/>
        <description>111111</description>
    </contact>


    <contact person="yasuo" tags="23">
        <name title="check">
            <first>sdf</first>
            <middle>1231</middle>
            <last>1231</last>
        </name>
        <location>
            <address>123</address>
            <latitude>123</latitude>
            <longitude>123</longitude>
        </location>
        <phone kind="12">10086</phone>
        <knows contacts="dasfa"/>
        <description>xdfasfadf</description>
    </contact>
    <contact person="yasuo" tags="23">
        <name title="check">
            <first>sdf</first>
            <middle>1231</middle>
            <last>1231</last>
        </name>
        <location>
            <address>123</address>
            <latitude>123</latitude>
            <longitude>123</longitude>
        </location>
        <phone kind="12">10086</phone>
        <knows contacts="dasfa"/>
        <description>uuuuu</description>
    </contact>


</contacts>
